test with pnetcdf

diff --git a/.github/workflows/miniconda.yml b/.github/workflows/miniconda.yml
--- a/.github/workflows/miniconda.yml
+++ b/.github/workflows/miniconda.yml
@@ -76,8 +76,15 @@ jobs:
         export PATH="${CONDA_PREFIX}/bin:${CONDA_PREFIX}/Library/bin:$PATH" 
         mpirun -np 4 --oversubscribe python mpi_example.py
         if [ $? -ne 0 ] ; then
-          echo "mpi test failed!"
+          echo "hdf5 mpi test failed!"
           exit 1
         else
-          echo "mpi test passed!"
+          echo "hdf5 mpi test passed!"
+        fi
+        mpirun -np 4 --oversubscribe python mpi_example.py NETCDF3_64BIT_DATA
+        if [ $? -ne 0 ] ; then
+          echo "pnetcdf mpi test failed!"
+          exit 1
+        else
+          echo "pnetcdf mpi test passed!"
         fi
