add mpi test

diff --git a/.github/workflows/miniconda.yml b/.github/workflows/miniconda.yml
--- a/.github/workflows/miniconda.yml
+++ b/.github/workflows/miniconda.yml
@@ -75,3 +75,11 @@ jobs:
       run: |
         source activate TEST
         cd test && python run_all.py
+        cd ../examples
+        mpirun.mpich -np 4 python mpi_example.py
+        if [ $? -ne 0 ] ; then
+          echo "mpi test failed!"
+          exit 1
+        else
+          echo "mpi test passed!"
+        fi
